### PR TITLE
tests: run on all PR

### PR DESCRIPTION
**Pull request by sbellone**
Renovate wasn't able to automerge this week's dependencies because the tests have not been run on the branches.
Indeed we were only running the workflows for branches targeting `master`.

Let's run tests on all PRs.

### CODE REVIEW

**Review by shortcuts — APPROVED** [review]
(I think if you put nothing it will work by default)

**Comment by sbellone** [comment]
You mean with an empty `types: []`?
I need to update it anyway because I see that it doesn't trigger when the PR is updated now :grimacing: 
I'll do the same than https://github.com/algolia/api-clients-automation/blob/main/.github/workflows/check.yml#L5

**Comment by shortcuts** [comment]
> You mean with an empty `types: []`? I need to update it anyway because I see that it doesn't trigger when the PR is updated now 😬 I'll do the same than https://github.com/algolia/api-clients-automation/blob/main/.github/workflows/check.yml#L5

I think if there's no `on` field it does nothing but otherwise yeah following what's on APIC is great :D

**Comment by sbellone** [comment]
Ok I'm trying with the defaults: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request

**Review by shortcuts — APPROVED** [review]

**Pull request merged**
